# client/Dockerfile
FROM node:18-alpine

WORKDIR /app

COPY client/package*.json ./

RUN npm install

COPY client/ .

# Build the React app
RUN npm run build

# Use a lightweight server for serving static files
FROM nginx:alpine
COPY --from=0 /app/dist /usr/share/nginx/html
EXPOSE 5173
CMD ["nginx", "-g", "daemon off;"]