# Shotweave-MVP/docker-compose.yml
version: '3.8'

services:
  # Flask Backend Service
  api:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: shotweave_api
    restart: always
    ports:
      - "5000:5000"
    volumes:
      - ./server/src:/app/src
      - ./server/.env:/app/.env
    # Depends on MongoDB (though external link is generally better)
    # depends_on:
    #   - mongo

  # React Frontend Service
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    container_name: shotweave_client
    restart: always
    ports:
      - "5173:5173"
    volumes:
      - ./client:/app
      - /app/node_modules
    environment:
      - VITE_API_URL=http://api:5000/api # Adjust proxy settings for Docker internal network
    depends_on:
      - api
      
  # MongoDB Service (Optional - for local dockerized DB)
  # mongo:
  #   image: mongo:latest
  #   container_name: shotweave_mongo
  #   ports:
  #     - "27017:27017"
  #   volumes:
  #     - mongo_data:/data/db

# volumes:
#   mongo_data: